app:
  ip-address: 192.168.90.59
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://server8887:8887/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: server8888
    prefer-ip-address: true
    ip-address: ${app.ip-address}
    appname: eureka-server
spring:
  application:
    name: eureka-server